/*
 * This source file was generated by the Gradle 'init' task
 */
package org.keepitsimple.draftlottery;

import static org.keepitsimple.draftlottery.TieredPowerball.simulateLottery;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        if (args.length == 0) {
            String[] defaultOrderedPlaces = {"1st", "2nd", "4th", "3rd", "8th", "7th",
                    "6th", "5th", "14th", "13th", "12th", "11th", "10th", "9th"};
            simulateLottery(System.out, defaultOrderedPlaces);
        } else {
            String[] orderedPlaces = args;
            simulateLottery(System.out, orderedPlaces);
        }
    }
}
